### ISSUE TITLE
Adding Primitive.true?(obj) and Primitive.false?(obj)

### ISSUE THREAD

**Issue by eregon** [andrykonchin/rubocop-truffleruby#1]
I think it'd be good to add `Primitive.true?(obj)` and `Primitive.false?(obj)` to replace `== true/false` and `.equal?(true/false)`.

**Comment by andrykonchin** [comment]
Solved in https://github.com/andrykonchin/rubocop-truffleruby/pull/4 and https://github.com/oracle/truffleruby/pull/3023
